# Generated by Django 6.0.2 on 2026-02-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="questions",
            new_name="question",
        ),
    ]
